trainer:
    accelerator: cpu
    devices: 1
    max_epochs: 200
    log_every_n_steps: 10
    deterministic: warn
model:
    num_classes: 4
    dropout_p: 0.5
    overfit: False
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 10
    gamma: 0.5
data:
    # data_dir_path: data/data/ShapeNetCore.v2_nbv
    batch_size: 32  # desired batch_size / devices
    num_train_objs: 200
    num_val_objs: 25
    num_test_objs: 25
